name: Build demo website

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.0'
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.113.0'
        extended: true
    - name: Build demo website
      working-directory: exampleSite
      run: hugo --minify